apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myReplicaSet
  labels:
    app: mywebsite
    tier: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: samplePod
  template:
    metadata:
      name: myPod
      labels:
        app: samplePod
    spec:
      containers:
        - name: sampleContainer
          image: sampleImage
